# Generated by Django 4.2.2 on 2023-06-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagem',
            options={'verbose_name_plural': 'Imagens'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
